name: LuxOS Pull-Request

on:
  pull_request:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  PACKAGE: luxos

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up runner 
        run: echo noop

      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Python toolchain
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Python dependencies
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install -r tests/requirements.txt

      - name: Run Python checks (ruff)
        shell: bash
        env:
          PYTHONPATH: src
        run: |
           ruff check src tests

      - name: Run Python checks (mypy)
        shell: bash
        env:
          PYTHONPATH: src
          OUTDIR: build/qa-${{ matrix.python-version }}-${{ matrix.os}}
        run: |
          mypy src \
            --no-incremental --xslt-html-report $OUTDIR/mypy

      - name: Run Python checks
        shell: bash
        env:
          PYTHONPATH: src
          OUTDIR: build/qa-${{ matrix.python-version }}-${{ matrix.os}}
        run: |
          py.test \
              --cov=${{ env.PACKAGE }} \
              --cov-report=html:$OUTDIR/coverage --cov-report=xml:$OUTDIR/coverage.xml \
              --junitxml=$OUTDIR/junit/junit.xml --html=$OUTDIR/junit/junit.html --self-contained-html \
            tests

      - name: Build wheel packages
        if: ${{ ! contains(matrix.os, 'windows') }}
        env:
          GITHUB_DUMP: ${{ toJson(github) }}
        run: |
          python -m build
          touch .keepme

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qa-results-${{ matrix.python-version }}-${{ matrix.os }}
          path: |
            build/qa-${{ matrix.python-version }}-${{ matrix.os}}
            dist
            .keepme
        # Use always() to always run this step to publish test results when there are test failures
        if: always()
